--------------------
-- STBase
-- By Spacetech
--------------------

STGamemodes.PlayerModels = {}
STGamemodes.InvalidPlayerModels = {}

STGamemodes.PlayerModels["Lilith"] = Model("models/mrgiggles/sassmodels/lilith-fix.mdl")

STGamemodes.PlayerModels["Breen"] = Model("models/player/breen.mdl")
STGamemodes.PlayerModels["Gordon"] = Model("models/Inaki/Characters/gordon_freeman.mdl")
STGamemodes.PlayerModels["Neo Combine"] = Model("models/player/neo_combine.mdl")
STGamemodes.PlayerModels["Sam"] = Model("models/player/sam.mdl")
STGamemodes.PlayerModels["Spacesuit"] = Model("models/player/spacesuit.mdl")
STGamemodes.PlayerModels["Battle Droid"] = Model("models/player/combine_droider.mdl")
STGamemodes.PlayerModels["Tron"] = Model("models/mrgiggles/sassmodels/tronplayer-fix.mdl")
STGamemodes.PlayerModels["Shepard"] = Model("models/mrgiggles/sassmodels/shepard-fix.mdl")
STGamemodes.PlayerModels["Onyx Guard"] = Model("models/mrgiggles/sassmodels/onyxguard-fix.mdl")
STGamemodes.PlayerModels["Zer0"] = Model("models/mrgiggles/sassmodels/zer0.mdl")

STGamemodes.PlayerModels["Barney"] = Model("models/player/barney.mdl")
STGamemodes.PlayerModels["Charple"] = Model("models/player/charple01.mdl")
STGamemodes.PlayerModels["Combine"] = Model("models/player/combine_soldier.mdl")
STGamemodes.PlayerModels["Eli"] = Model("models/player/eli.mdl")
STGamemodes.PlayerModels["Fast Zombie"] = Model("models/player/zombie_fast.mdl")
STGamemodes.PlayerModels["G-Man"] = Model("models/player/gman_high.mdl")
STGamemodes.PlayerModels["Kleiner"] = Model("models/player/Kleiner.mdl")
STGamemodes.PlayerModels["Mossman"] = Model("models/player/mossman.mdl")
STGamemodes.PlayerModels["Odessa"] = Model("models/player/odessa.mdl")
STGamemodes.PlayerModels["Police"] = Model("models/player/police.mdl")
STGamemodes.PlayerModels["Prison"] = Model("models/player/combine_soldier_prisonguard.mdl")
STGamemodes.PlayerModels["Stripped"] = Model("models/player/soldier_stripped.mdl")
STGamemodes.PlayerModels["Super"] = Model("models/player/combine_super_soldier.mdl")
STGamemodes.PlayerModels["Zombie"] = Model("models/player/zombie_classic.mdl")

STGamemodes.PlayerModels["Arctic"] = Model("models/player/arctic.mdl")
STGamemodes.PlayerModels["Gasmask"] = Model("models/player/gasmask.mdl")
STGamemodes.PlayerModels["Guerilla"] = Model("models/player/guerilla.mdl")
STGamemodes.PlayerModels["Leet"] = Model("models/player/leet.mdl")
STGamemodes.PlayerModels["Phoenix"] = Model("models/player/Phoenix.mdl")
STGamemodes.PlayerModels["Riot"] = Model("models/player/riot.mdl")
STGamemodes.PlayerModels["Swat"] = Model("models/player/swat.mdl")
STGamemodes.PlayerModels["Urban"] = Model("models/player/urban.mdl")

STGamemodes.PlayerModels["Female 1"] = Model("models/player/Group01/female_01.mdl")
STGamemodes.PlayerModels["Female 2"] = Model("models/player/Group01/female_02.mdl")
STGamemodes.PlayerModels["Female 3"] = Model("models/player/Group01/female_03.mdl")
STGamemodes.PlayerModels["Female 4"] = Model("models/player/Group01/female_04.mdl")
STGamemodes.PlayerModels["Female 5"] = Model("models/player/Group01/female_05.mdl")
STGamemodes.PlayerModels["Female 6"] = Model("models/player/Group01/female_06.mdl")
STGamemodes.PlayerModels["Female 7"] = Model("models/player/Group03/female_01.mdl")
STGamemodes.PlayerModels["Female 8"] = Model("models/player/Group03/female_02.mdl")
STGamemodes.PlayerModels["Female 9"] = Model("models/player/Group03/female_03.mdl")
STGamemodes.PlayerModels["Female 10"] = Model("models/player/Group03/female_04.mdl")
STGamemodes.PlayerModels["Female 11"] = Model("models/player/Group03/female_05.mdl")
STGamemodes.PlayerModels["Female 12"] = Model("models/player/Group03/female_06.mdl")

STGamemodes.PlayerModels["Male 1"] = Model("models/player/Group01/male_01.mdl")
STGamemodes.PlayerModels["Male 2"] = Model("models/player/Group01/male_02.mdl")
STGamemodes.PlayerModels["Male 3"] = Model("models/player/Group01/male_03.mdl")
STGamemodes.PlayerModels["Male 4"] = Model("models/player/Group01/male_04.mdl")
STGamemodes.PlayerModels["Male 5"] = Model("models/player/Group01/male_05.mdl")
STGamemodes.PlayerModels["Male 6"] = Model("models/player/Group01/male_06.mdl")
STGamemodes.PlayerModels["Male 7"] = Model("models/player/Group01/male_07.mdl")
STGamemodes.PlayerModels["Male 8"] = Model("models/player/Group01/male_08.mdl")
STGamemodes.PlayerModels["Male 9"] = Model("models/player/Group01/male_09.mdl")
STGamemodes.PlayerModels["Male 10"] = Model("models/player/Group03/male_01.mdl")
STGamemodes.PlayerModels["Male 11"] = Model("models/player/Group03/male_02.mdl")
STGamemodes.PlayerModels["Male 12"] = Model("models/player/Group03/male_03.mdl")
STGamemodes.PlayerModels["Male 13"] = Model("models/player/Group03/male_04.mdl")
STGamemodes.PlayerModels["Male 14"] = Model("models/player/Group03/male_05.mdl")
STGamemodes.PlayerModels["Male 15"] = Model("models/player/Group03/male_06.mdl")
STGamemodes.PlayerModels["Male 16"] = Model("models/player/Group03/male_07.mdl")
STGamemodes.PlayerModels["Male 17"] = Model("models/player/Group03/male_08.mdl")
STGamemodes.PlayerModels["Male 18"] = Model("models/player/Group03/male_09.mdl")

STGamemodes.PlayerModels["Hostage 1"] = Model("models/player/Hostage/Hostage_01.mdl")
STGamemodes.PlayerModels["Hostage 2"] = Model("models/player/Hostage/Hostage_02.mdl")
STGamemodes.PlayerModels["Hostage 3"] = Model("models/player/Hostage/Hostage_03.mdl")
STGamemodes.PlayerModels["Hostage 4"] = Model("models/player/Hostage/Hostage_04.mdl")
